# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='local',
            field=models.CharField(default=20, max_length=15),
            preserve_default=False,
        ),
    ]
