# Generated by Django 3.0.2 on 2020-02-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_personal_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_id', models.IntegerField()),
                ('cargo_id', models.IntegerField(blank=True, null=True)),
                ('dependencia_id', models.IntegerField(blank=True, null=True)),
                ('manual_cargo_id', models.IntegerField(blank=True, null=True)),
                ('descripcion_cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_inst', models.CharField(blank=True, max_length=60, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=60, null=True)),
                ('estatus', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_personal_id', models.IntegerField(blank=True, null=True)),
                ('des_tipo_personal', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_clave', models.DateTimeField()),
                ('tin_parroquia_id', models.IntegerField(blank=True, null=True)),
                ('zona_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tlf_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('tlf_local', models.CharField(blank=True, max_length=20, null=True)),
                ('tlf_personal', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('salt', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tin_usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
