# Generated by Django 3.0.2 on 2020-03-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_auto_20200217_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TinDependencias',
        ),
    ]
